export const styles = {
  header: [
    "flex-auto",
    "flex",
    "align-items-start",
    "flex-column",
    "lg:justify-content-between",
    "lg:flex-row",
  ],
  headerContent: ["flex", "flex-auto", "flex-column", "align-items-center"],
  headerSubcontent: ["flex", "align-items-center", "text-700", "flex-wrap"],
  headerSubtext: ["mr-5", "mt-3", "flex", "align-items-center"],
  headerText: ["font-medium", "text-3xl", "text-900"],
  mobileBar: [
    "flex",
    "justify-content-center",
    "bg-yellow-500 border-round text-white font-bold px-5 py-3 mx-2 mb-2",
  ],
  notificationBar: [
    "flex-auto",
    "flex",
    "align-items-center",
    "justify-content-center",
    "bg-blue-500",
    "font-bold",
    "text-white",
    "m-2",
    "px-5",
    "py-3",
    "border-round",
  ],
  productPanel: ["flex", "flex-column", "justify-content-start"],
  productPanelHeader: ["flex", "flex-row", "justify-content-evenly"],
  timeIcon: ["pi", "pi-clock", "mr-2"],
};
