export const styles = {
  footer: ["mt-3", "md:py-3", "bg-bluegray-100", "border-round", "opacity-80"],
  footerButton: [
    "p-button-rounded",
    "p-button-link",
    "p-button-lg",
    "text-bluegray-600",
    "text-sm",
  ],
  header: [
    "flex-auto",
    "flex",
    "align-items-start",
    "flex-column",
    "lg:justify-content-between",
    "lg:flex-row",
  ],
  headerContent: ["flex", "flex-auto", "flex-column", "align-items-center"],
  headerSubcontent: ["flex", "align-items-center", "text-700", "flex-wrap"],
  headerSubtext: ["mr-5", "mt-3", "flex", "align-items-center"],
  headerText: ["font-medium", "text-3xl", "text-900"],
  mobileBar: [
    "flex",
    "justify-content-center",
    "bg-yellow-500 border-round text-white font-bold px-5 py-3 mb-2",
  ],
  notificationBar: [
    "flex-auto",
    "flex",
    "align-items-center",
    "justify-content-center",
    "bg-blue-700",
    "font-bold",
    "text-white",
    "my-2",
    "px-5",
    "py-3",
    "border-round",
  ],
  productPanel: ["flex", "flex-column", "justify-content-start"],
  productPanelHeader: ["flex", "flex-row", "justify-content-evenly"],
  sectionTitle: ["mt-3", "px-3", "pt-3", "font-bold", "text-lg"],
  timeIcon: ["pi", "pi-clock", "mr-2"],
};
